# Generated by Django 2.2 on 2019-05-01 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='user_name',
            new_name='user_id',
        ),
    ]
